import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { lazy, Suspense } from "react";
import "./globals.css";

const Navbar = lazy(() => import("./component/Navbar"));
const Footer = lazy(() => import("./component/Footer"));
const Clock = lazy(() => import("./component/ui/clock").then(mod => ({ default: mod.Clock })));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { BookingProvider } from "./BookingContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BookingProvider>
          <header className="sticky top-0 z-50 shadow-md">
            <Suspense fallback={<div>Loading Clock...</div>}>
              <Clock />
            </Suspense>
            <Suspense fallback={<div>Loading Navbar...</div>}>
              <Navbar />
            </Suspense>
          </header>
          <main>
            {children}
          </main>
          <Suspense fallback={<div>Loading Footer...</div>}>
            <Footer />
          </Suspense>
        </BookingProvider>
      </body>
    </html>
  );
}
